jobs:
  build:
    docker:
      - image: cimg/node:18.12.0

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "yarn.lock" }}'
            - v1-dependencies-

      - run: yarn install
      - run: yarn build

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run: yarn test:e2e:ci

  deploy-staging:
    executor: heroku/default

    working_directory: ~/repo

    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          app-name: staging-adms-ui
          force: true

  deploy-production:
    executor: heroku/default

    working_directory: ~/repo

    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          app-name: production-adms-ui

version: 2.1
orbs:
  heroku: circleci/heroku@1.2.6
workflows:
  build-test-deploy:
    jobs:
      - build:
          context: staging-adms-ui
      - deploy-staging:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
      - deploy-production:
          requires:
            - build
          filters:
            branches:
              only:
                - main
